[package]
name = "forth"
version = "0.0.1"
authors = ["Jon Edwards <jkedwards@me.com>"]
edition = "2018"

[dependencies]
cursive = { version = "0.15.0", features = ["toml"] }
machine = "0.3.0"
rand = "0.7.3"
